name: Cypress
on: [push, pull_request]

env:
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies and run
        run: |
          cd ./solutions/02_Setup/cypress
          npm i
          cd ../
          sudo chmod -R 777 tests/
          npx saucectl run -c .sauce/config.yml
          echo $?
        env:
          BUILD_ID: ${{ github.run_id }}
          BUILD_ENV: GitHub Actions